### PR TITLE
Ändringar i outputformatet mm

### PR DESCRIPTION
**Pull request by torandi**
Ändrade lite i hur outputformatet ser ut, så upp till dig om du vill ha den här eller inte. Gjode dessutom bitly-förkortningen optional (genom att man inte specar det i confen helt enkelt)

New format:
<nick>'s URL title: <title> [| short url]

if bitly is not set in the config no url is outputed after the title

### CODE REVIEW

**Comment by Frost** [comment]
Skriv på engelska ffs!

This is only the output format in the channel, and not in the html file, right? Also, have you verified that this works?

**Comment by torandi** [comment]
I have verified that this works. And it only modifies the output in the channel.

**Comment by p-blomberg** [comment]
I think the current (old) format is better. I would prefer a cleaner format like `[Frost] foo` where foo is the title.

On the other hand... http://en.wiktionary.org/wiki/bikeshedding

**Comment by Frost** [comment]
@p-blomberg I like your format better, and I might just change it again. I'll probably make that the default, and also make it overrideable in the config. How about that?

**Comment by p-blomberg** [comment]
Making it configurable sounds like a good idea. That means everyone can bikeshed as much as they want. =)

**Comment by Frost** [comment]
Fix'd (#22) with default format `[Frost] title - short_url`

**Pull request merged**
